/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author felip
 */
public class introducao extends javax.swing.JFrame {

    /**
     * Creates new form introducao
     */
    public introducao() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblReminder = new javax.swing.JLabel();
        lblDica = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(22, 227, 127));
        kGradientPanel1.setkStartColor(new java.awt.Color(11, 110, 62));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(113, 113, 113));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sustentabilidade na engenharia civil");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 432, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/capacete.png"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 186, 267, 186));

        lblReminder.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblReminder.setForeground(new java.awt.Color(255, 255, 255));
        lblReminder.setText("<html>Antes de começar o desafio leia atentamente<br> a introdução a seguir para ter uma performance melhor !</html>");
        kGradientPanel1.add(lblReminder, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));
        lblReminder.getAccessibleContext().setAccessibleName("Antes de começar o desafio leia atentamente \\na introdução a seguir para ter uma performance melhor !");

        lblDica.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDica.setForeground(new java.awt.Color(255, 255, 255));
        lblDica.setText("<html> A Sustentabilidade na Engenharia Civil é uma\nforma de se construir casas e<br> edifícios,\nharmonizado-os com o meio <br>ambiente. Ela procura, \ndurante sua contrução e pós-construção, amenizar<br>\nos impactos à natureza, reduzindo o máximo\npossível os resíduos e utilizando com \neficiência os materiais e bens naturais \ncomo água e energia. <br>\nA partir deste conceito, é necessário<br>\no uso de materiais reciclaveis e que <br>\nnão agridam o meio ambiente.");
        kGradientPanel1.add(lblDica, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 223, 250));

        kButton1.setForeground(new java.awt.Color(0, 0, 0));
        kButton1.setText("Entendido");
        kButton1.setkEndColor(new java.awt.Color(113, 113, 113));
        kButton1.setkHoverEndColor(new java.awt.Color(11, 110, 62));
        kButton1.setkHoverForeGround(new java.awt.Color(22, 227, 127));
        kButton1.setkHoverStartColor(new java.awt.Color(11, 110, 62));
        kButton1.setkStartColor(new java.awt.Color(151, 151, 151));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_kButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(introducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(introducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(introducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(introducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new introducao().setVisible(true);
            }
        });
    }

    public void remider() {
        lblReminder.setText("Aqui está uma dica para você !");
    }

    public void dica() {
        lblDica.setText("<html>A energia solar é uma forma prática e barata"
                + " de se conseguir energia<br> sem prejudicar o meio ambiente !</html>");
    }

    public void dica1() {
        lblDica.setText("<html>Isolamento térmico: nos dias de muito calor, as telhas"
                + " convencionais podem <br>marcar mais de 50°C</html>");
    }

    public void dica2() {
        lblDica.setText("<html>Recursos naturais são de grande ajuda tanto econômica"
                + "quanto sustentável. A <br>energia solar é um ótimo exemplo </html>");
    }

    public void dica3() {
        lblDica.setText("<html>O plástico agride o meio ambiente e demora para se decomopor<br>"
                + "tente utilizar algo diferente ! </html>");
    }

    public void dica4() {
        lblDica.setText("<html>o Green Building é um espaço que deve utilizar processos"
                + "de sustentabilidade<br> na construção civil em toda a sua concepção, construção e operação, gerando<br>"
                + "benefícios econômicos e à saúde.</html>");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private keeptoo.KButton kButton1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblDica;
    private javax.swing.JLabel lblReminder;
    // End of variables declaration//GEN-END:variables
}
